### ISSUE TITLE
Frames not extracting correctly so no charms found

### ISSUE THREAD

**Issue by Styrofoam12** [chpoit/utsushis-charm#42]
**Device**
- PC
  - For PC, what is your screen resolution: 3440x1440
  - For PC, what is your OS: Win 10
  - Using windows capture
- Game language: English

- App version: 1.7.1

** Problem(s) **
After installing everything and clipping I found every frame it extracts is fractured or parsed poorly (Screenshot below). Following some troubleshooting you've posted both here and reddit I tried:
 - Different resolutions for windows capture, and game capture
 - Different locations in game to reduce noise
 - Full restart / clean of directories and remade captures
I am unsure how to proceed or what to troubleshoot next. 
Below is a screenshot of what every frame looks like, two different captures, and the logs.

![frame173](https://user-images.githubusercontent.com/6199693/181280799-425a2d26-9303-4d35-801f-b07da8918960.png)

https://user-images.githubusercontent.com/6199693/181281905-50612b63-43d8-4443-b590-a7594890a686.mp4

https://user-images.githubusercontent.com/6199693/181281941-ea844552-3c90-4de7-9afb-1a764b64944e.mp4

[app.log](https://github.com/chpoit/utsushis-charm/files/9200313/app.log)

```Input video location:  inputs
Frame location:  frames
Autosaving Charms:  True
Skipping frame extraction:  False
Deleting existing frames:  False
Extracting Frames
Total input files to scan: 1


Reduced frames from 380 to 368
Extracting charms from frames
Checking for bundled tesseract
Tesseract: ...\libtesseract-5.dll (removed my user)
Language pack was found```
![image](https://user-images.githubusercontent.com/6199693/181282353-9e973e6f-c312-436d-9552-cc8be3404856.png)

**Comment by chpoit** [comment]
Thanks for the issue. Your game must absolutely run in a 16:9 aspect ratio (ex 1920x1080, 2440x1440 or 3840x2160). You are running a 21:9 aspect ratio. Please try setting your game to either one of those resolutions. If you pick 1440p and check the "remove black bars" option it *should* grab the black bars that will appear on the sides and remove them allowing for proper extraction.

From the first clip you sent I can see that there are huge black bars at the top and bottom, which is probably because you only change the capture resolution, and not the game resolution. clips you sent it seems that you 

I'll try and see if I can add 21:9 support now that I have your second clip (I don't own a 21:9 monitor, or the game on PC, so I could never do anything about it), but it will take a while. In the meantime, please try what I outlined in the first paragraph.

**Comment by Styrofoam12** [comment]
Update: I'm a dope. I changed the resolution but never changed the aspect ratio in the settings. Changing that to 16:9 the app works as expected. Thanks for troubleshooting my reading skills!

**Comment by chpoit** [comment]
Let me know if 1.8 works properly with your 21:9 recordings, they should, but it's mostly experimental.
